
services:
    botpress:
        image: botpress/server
        ports:
        - 3001:3000
        container_name: botpress
        volumes:
        - botpress-data:/app/data
        environment:
        - API_URL=${API_URL}
        networks:
        - botpress


volumes:
  botpress-data:
  
networks:
  botpress:
    external: true

